name: Deploy to server
on: 
  push:
    branches: [master]
  
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VUE_APP_GRAPHQL_HTTP: ${{ secrets.GRAPHQL_URL }}
          envkey_VUE_APP_REST_HTTP: ${{ secrets.REST_URL }}
          envkey_VUE_APP_COOKIE_DOMAIN: ${{ secrets.COOKIE_DOMAIN }}
      
      - name: Build project
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      
      - name: Create docker container
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "xanderv2001/pc-parts-frontend"
          LATEST: "true" 
      
      - name: Update server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker pull xanderv2001/pc-parts-frontend
            sudo docker stop pcpartsfrontend
            sudo docker rm pcpartsfrontend
            sudo docker run --name pcpartsfrontend --restart always -p 127.0.0.1:4100:8080 -d xanderv2001/pc-parts-frontend
            sudo docker image prune -f